import json

with open("app/ml/train_rl.ipynb", "r") as f:
    nb = json.load(f)

# Find the training script cell
script_idx = -1
for i, cell in enumerate(nb["cells"]):
    if cell["cell_type"] == "code" and any("import fastf1" in line for line in cell["source"]):
        script_idx = i
        break

if script_idx != -1:
    new_source = []
    lines = [
        "import fastf1\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import gymnasium as gym\n",
        "from gymnasium import spaces\n",
        "from stable_baselines3 import PPO\n",
        "from stable_baselines3.common.vec_env import DummyVecEnv\n",
        "import os\n",
        "import random\n",
        "\n",
        "# Driver Personality Traits\n",
        "DRIVER_TRAITS = {\n",
        "    'VER': {'aggression': 0.95, 'consistency': 0.90, 'wet_skill': 0.95, 'tire_management': 0.85, 'risk_tolerance': 0.90},\n",
        "    'HAM': {'aggression': 0.85, 'consistency': 0.95, 'wet_skill': 0.95, 'tire_management': 0.95, 'risk_tolerance': 0.80},\n",
        "    'NOR': {'aggression': 0.88, 'consistency': 0.85, 'wet_skill': 0.85, 'tire_management': 0.80, 'risk_tolerance': 0.85},\n",
        "    'LEC': {'aggression': 0.90, 'consistency': 0.88, 'wet_skill': 0.85, 'tire_management': 0.85, 'risk_tolerance': 0.85},\n",
        "}\n",
        "DEFAULT_TRAITS = {'aggression': 0.5, 'consistency': 0.5, 'wet_skill': 0.5, 'tire_management': 0.5, 'risk_tolerance': 0.5}\n",
        "\n",
        "# 1. Setup FastF1 Cache\n",
        "os.makedirs('./f1_cache', exist_ok=True)\n",
        "fastf1.Cache.enable_cache('./f1_cache')\n",
        "\n",
        "seasons = [2024, 2025]\n",
        "drivers = ['VER', 'HAM', 'NOR', 'LEC']\n",
        "\n",
        "all_telemetry = []\n",
        "\n",
        "print(\"Fetching high-frequency telemetry across 2024 & 2025 seasons...\")\n",
        "for season in seasons:\n",
        "    schedule = fastf1.get_event_schedule(season)\n",
        "    # Filter out testing events, keeping only real races\n",
        "    races = schedule[schedule['EventFormat'] != 'testing']['EventName'].tolist()\n",
        "    for track in races:\n",
        "        try:\n",
        "            print(f\"-> Fetching {season} {track}...\")\n",
        "            session = fastf1.get_session(season, track, 'R')\n",
        "            session.load(telemetry=True, laps=True, weather=False, messages=False)\n",
        "            \n",
        "            for driver in drivers:\n",
        "                try:\n",
        "                    fastest_lap = session.laps.pick_driver(driver).pick_fastest()\n",
        "                    telemetry = fastest_lap.get_telemetry()\n",
        "                    t_data = telemetry[['Distance', 'Speed', 'Throttle', 'Brake', 'nGear', 'X', 'Y', 'Z']].fillna(0).copy()\n",
        "                    \n",
        "                    # Inject personality traits into the DataFrame\n",
        "                    traits = DRIVER_TRAITS.get(driver, DEFAULT_TRAITS)\n",
        "                    t_data['aggression'] = traits['aggression']\n",
        "                    t_data['consistency'] = traits['consistency']\n",
        "                    t_data['wet_skill'] = traits['wet_skill']\n",
        "                    t_data['tire_management'] = traits['tire_management']\n",
        "                    t_data['risk_tolerance'] = traits['risk_tolerance']\n",
        "                    \n",
        "                    if len(t_data) > 100:\n",
        "                        all_telemetry.append(t_data)\n",
        "                except Exception:\n",
        "                    pass\n",
        "        except Exception as e:\n",
        "            print(f\"   Failed/Skipped {season} {track}: {e}\")\n",
        "\n",
        "if not all_telemetry:\n",
        "    raise ValueError(\"No telemetry data was successfully downloaded!\")\n",
        "print(f\"\\nSuccessfully loaded {len(all_telemetry)} expert lap sequences for training.\")\n",
        "\n",
        "# 2. Build the RL Environment\n",
        "class F1TelemetryEnv(gym.Env):\n",
        "    def __init__(self, telemetry_datasets):\n",
        "        super(F1TelemetryEnv, self).__init__()\n",
        "        self.datasets = telemetry_datasets\n",
        "        self.expert_data = self.datasets[0]\n",
        "        self.max_steps = len(self.expert_data) - 1\n",
        "        \n",
        "        # Action Space: [Steering, Throttle, Brake]\n",
        "        self.action_space = spaces.Box(low=np.array([-1.0, 0.0, 0.0]), \n",
        "                                     high=np.array([1.0, 1.0, 1.0]), \n",
        "                                     dtype=np.float32)\n",
        "        \n",
        "        # Observation Space: [Speed, X, Y, Heading, 5*LiDAR, 5*Personality Traits] = 14 dimensions\n",
        "        self.observation_space = spaces.Box(low=-np.inf, high=np.inf, shape=(14,), dtype=np.float32)\n",
        "        self.current_step = 0\n",
        "\n",
        "    def reset(self, seed=None):\n",
        "        super().reset(seed=seed)\n",
        "        self.expert_data = random.choice(self.datasets)\n",
        "        self.max_steps = len(self.expert_data) - 1\n",
        "        self.current_step = 0\n",
        "        return self._get_obs(), {}\n",
        "\n",
        "    def _get_obs(self):\n",
        "        row = self.expert_data.iloc[self.current_step]\n",
        "        return np.array([\n",
        "            row['Speed'], row['X'], row['Y'], 0.0, \n",
        "            20.0, 20.0, 30.0, 20.0, 20.0, # Track boundaries / raycasts\n",
        "            row['aggression'], row['consistency'], row['wet_skill'], \n",
        "            row['tire_management'], row['risk_tolerance']\n",
        "        ], dtype=np.float32)\n",
        "\n",
        "    def step(self, action):\n",
        "        expert_row = self.expert_data.iloc[self.current_step]\n",
        "        \n",
        "        expert_throttle = expert_row['Throttle'] / 100.0\n",
        "        expert_brake = 1.0 if expert_row['Brake'] else 0.0\n",
        "        \n",
        "        throttle_diff = abs(action[1] - expert_throttle)\n",
        "        brake_diff = abs(action[2] - expert_brake)\n",
        "        \n",
        "        reward = 10.0 - (throttle_diff * 5.0) - (brake_diff * 5.0)\n",
        "        \n",
        "        self.current_step += 1\n",
        "        terminated = self.current_step >= self.max_steps\n",
        "        truncated = False\n",
        "        \n",
        "        return self._get_obs(), reward, terminated, truncated, {}\n",
        "\n",
        "# 3. Train the Model\n",
        "print(\"\\nInitializing RL Environment...\")\n",
        "env = DummyVecEnv([lambda: F1TelemetryEnv(all_telemetry)])\n",
        "\n",
        "print(\"Training PPO Agent over massive dataset (This will take a while)...\")\n",
        "model = PPO(\"MlpPolicy\", env, verbose=1, device=\"auto\")\n",
        "model.learn(total_timesteps=300_000) # Increased timesteps for larger data\n",
        "\n",
        "# 4. Save locally\n",
        "print(\"Saving Model...\")\n",
        "os.makedirs(\"models\", exist_ok=True)\n",
        "model.save(\"models/ppo_f1_driver.zip\")\n",
        "print(\"\u2705 Massive Training Complete! Generalized model saved.\")\n"
    ]
    nb["cells"][script_idx]["source"] = lines
    
    with open("app/ml/train_rl.ipynb", "w") as f:
        json.dump(nb, f, indent=1)
        
